/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function ModelAlgarrobico(props) {
  const { nodes, materials } = useGLTF("/Algarrobico_.gltf");

  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.64, 3.89, -1.09]}
        rotation={[0, -1.33, 0]}
        scale={0.62}
      >
        <group position={[4.01, -2.43, 4.03]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Edificios001"].geometry}
            material={props.get(materials.Edificios)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas007"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas008"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas009"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas010"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas011"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Algarrobico-Ventanas012"].geometry}
            material={props.get(materials["Ventanas.003"])}
          />
        </group>
        <group position={[1.63, 2.79, -1.09]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Gruas-Gruas002"].geometry}
            material={props.get(materials.Gruas)}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Gruas-Gruas003"].geometry}
            material={props.get(materials.Gruas)}
          />
        </group>
        <group position={[-4.16, 0.89, 2.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Matojos-Matojos001"].geometry}
            material={props.get(materials.Matojos)}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Agua001.geometry}
          material={props.get(materials.Agua)}
          position={[13.87, -5.22, 0.48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carretera001.geometry}
          material={props.get(materials["Carretera.004"])}
          position={[-5.47, -0.44, 7.39]}
          rotation={[0, 0, -0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carretera_Playa001.geometry}
          material={props.get(materials["Carretera.004"])}
          position={[8.9, -3.37, 1.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Terreno003.geometry}
          material={props.get(materials["Terreno.3"])}
          position={[-10.99, -3.51, -5.38]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Terreno002.geometry}
          material={props.get(materials["Terreno.2"])}
          position={[-10.99, -4.1, -5.38]}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.9}
        position={[0, 1.81, 13.37]}
        rotation={[-0.14, -0.17, -0.02]}
      />
    </group>
  );
}

useGLTF.preload("/Algarrobico_.gltf");
