/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function ModelCupula(props) {
  const { nodes, materials } = useGLTF("/Cupula_.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[52.3, 157.1, 423.8]}>
          <group position={[-80.33, 33.63, -269.79]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Arboles3-Arboles002"].geometry}
              material={materials.Arboles}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Arboles3-Troncos002"].geometry}
              material={materials["Troncos.001"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Carretera002.geometry}
            material={materials["Carretera.1"]}
            position={[108.68, -40.43, 449.59]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Edificios002.geometry}
            material={materials["Material.001"]}
            position={[-75.52, 119.33, -204.58]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Peana002.geometry}
            material={materials["Terreno.1"]}
            position={[23.58, -88.93, 12.39]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Terreno002.geometry}
            material={materials["Terreno.3"]}
            position={[23.58, -23.6, 12.39]}
          />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.9}
        rotation={[-0.33, -0.25, -0.08]}
      />
    </group>
  );
}

useGLTF.preload("/Cupula_.gltf");
