/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function ModelBunielUrbanizacion(props) {
  const { nodes, materials } = useGLTF("/Buniel_urbanizacion.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -3.39, 0]} scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arboles.geometry}
          material={materials.Matojos}
          position={[1720.6, 1312.9, 6801.05]}
          scale={3.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base.geometry}
          material={materials["Terreno.2"]}
          position={[2515.7, 1000.06, 1787.08]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carreteras.geometry}
          material={materials["Carretera.002"]}
          position={[0, 2409.69, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EDIFICIOS.geometry}
          material={materials.Edificios}
          position={[10254.57, 1658.7, 10213.63]}
          scale={3.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Escombros.geometry}
          material={materials.Edificios}
          position={[1936.54, 1340.16, 6494.13]}
          scale={3.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TERRENO.geometry}
          material={materials["Terreno.3"]}
          position={[2503.55, 1227.18, 1782.87]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.9}
        rotation={[-0.58, -0.95, -0.49]}
      />
    </group>
  );
}

useGLTF.preload("/Buniel_urbanizacion.gltf");
